"""added last_notification_read column to user table

Revision ID: 039ce4e121cc
Revises: 9a728770bba1
Create Date: 2022-08-18 11:42:03.679996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039ce4e121cc'
down_revision = '9a728770bba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_notification_read', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_notification_read')
    # ### end Alembic commands ###
