"""Fixing spelling mistake

Revision ID: 0455d2c7075d
Revises: 2a0855ff40d9
Create Date: 2019-11-15 08:34:07.948131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0455d2c7075d'
down_revision = '2a0855ff40d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('qualification', sa.Boolean(), nullable=True))
    op.drop_column('turkcode', 'qualtification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('qualtification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('turkcode', 'qualification')
    # ### end Alembic commands ###
