"""Added Survey ID to Turkcodes

Revision ID: 05847408d7be
Revises: d338b4365023
Create Date: 2019-12-20 09:08:27.298907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05847408d7be'
down_revision = 'd338b4365023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('survey_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_turkcode_survey_id'), 'turkcode', ['survey_id'], unique=False)
    op.create_foreign_key(None, 'turkcode', 'survey', ['survey_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turkcode', type_='foreignkey')
    op.drop_index(op.f('ix_turkcode_survey_id'), table_name='turkcode')
    op.drop_column('turkcode', 'survey_id')
    # ### end Alembic commands ###
