"""Added examined column to cluster table

Revision ID: 06614d80dad0
Revises: e8a1a55fd4d6
Create Date: 2021-04-14 10:21:40.861519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06614d80dad0'
down_revision = 'e8a1a55fd4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('examined', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_cluster_examined'), 'cluster', ['examined'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_examined'), table_name='cluster')
    op.drop_column('cluster', 'examined')
    # ### end Alembic commands ###
