"""Added processing column to trapgroups

Revision ID: 0723835f30da
Revises: 7cd5443ad09f
Create Date: 2020-05-05 17:30:22.074811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0723835f30da'
down_revision = '7cd5443ad09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trapgroup', sa.Column('processing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trapgroup', 'processing')
    # ### end Alembic commands ###
