"""Added zip table and archive cols

Revision ID: 0930654cca55
Revises: 4b1da15ff6e8
Create Date: 2024-11-06 10:09:18.796733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0930654cca55'
down_revision = '4b1da15ff6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zip_expiry_date'), 'zip', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_zip_survey_id'), 'zip', ['survey_id'], unique=False)
   
    op.add_column('image', sa.Column('zip_id', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_image_expiry_date'), 'image', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_image_zip_id'), 'image', ['zip_id'], unique=False)
    op.create_foreign_key(None, 'image', 'zip', ['zip_id'], ['id'])
    
    op.add_column('survey', sa.Column('require_launch', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_survey_require_launch'), 'survey', ['require_launch'], unique=False)
  
    op.add_column('task', sa.Column('empty_count', sa.Integer(), nullable=True))

    op.add_column('video', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_video_expiry_date'), 'video', ['expiry_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_video_expiry_date'), table_name='video')
    op.drop_column('video', 'expiry_date')
   
    op.drop_column('task', 'empty_count')
    
    op.drop_index(op.f('ix_survey_require_launch'), table_name='survey')
    op.drop_column('survey', 'require_launch')
   
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_index(op.f('ix_image_zip_id'), table_name='image')
    op.drop_index(op.f('ix_image_expiry_date'), table_name='image')
    op.drop_column('image', 'expiry_date')
    op.drop_column('image', 'zip_id')

    op.drop_index(op.f('ix_zip_survey_id'), table_name='zip')
    op.drop_index(op.f('ix_zip_expiry_date'), table_name='zip')
    op.drop_table('zip')
    # ### end Alembic commands ###
