"""Added flank and aid cols to detection

Revision ID: 0ad045f609b9
Revises: c6da7222b204
Create Date: 2024-05-31 06:33:45.286878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ad045f609b9'
down_revision = 'c6da7222b204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('flank', sa.String(length=1), nullable=True))
    op.add_column('detection', sa.Column('aid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_detection_aid'), 'detection', ['aid'], unique=False)
    op.create_index(op.f('ix_detection_flank'), 'detection', ['flank'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_flank'), table_name='detection')
    op.drop_index(op.f('ix_detection_aid'), table_name='detection')
    op.drop_column('detection', 'aid')
    op.drop_column('detection', 'flank')
    # ### end Alembic commands ###
