"""Added classification info to detection table.

Revision ID: 0c9610b64864
Revises: baeb6832abcc
Create Date: 2020-11-03 16:27:11.512334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9610b64864'
down_revision = 'baeb6832abcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('class_score', sa.Float(), nullable=True))
    op.add_column('detection', sa.Column('classification', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_detection_class_score'), 'detection', ['class_score'], unique=False)
    op.create_index(op.f('ix_detection_classification'), 'detection', ['classification'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_classification'), table_name='detection')
    op.drop_index(op.f('ix_detection_class_score'), table_name='detection')
    op.drop_column('detection', 'classification')
    op.drop_column('detection', 'class_score')
    # ### end Alembic commands ###
