"""added extracted timestamp column to video table

Revision ID: 0dae8a55964f
Revises: dbda7bd631a8
Create Date: 2024-02-29 07:00:28.654504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dae8a55964f'
down_revision = 'dbda7bd631a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('extracted_timestamp', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'extracted_timestamp')
    # ### end Alembic commands ###
