"""Added related_check_count column to task table

Revision ID: 0e4cdc7aae95
Revises: 4643351c7899
Create Date: 2025-02-21 08:19:36.518533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4cdc7aae95'
down_revision = '4643351c7899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('related_check_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'related_check_count')
    # ### end Alembic commands ###
