"""Added trapgroup code to surveys.

Revision ID: 1423b6625c9e
Revises: 05847408d7be
Create Date: 2020-01-13 06:57:41.444500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1423b6625c9e'
down_revision = '05847408d7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('trapgroup_code', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'trapgroup_code')
    # ### end Alembic commands ###
