"""Renamed image hash column to etag

Revision ID: 19f5d9426d42
Revises: 63d5be617c46
Create Date: 2023-02-17 11:54:24.802737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19f5d9426d42'
down_revision = '63d5be617c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('image', sa.Column('etag', sa.String(length=64), nullable=True))
    op.drop_index('ix_image_hash', table_name='image')
    op.alter_column('image', 'hash', nullable=True, new_column_name='etag',existing_type=sa.String(length=64))
    op.create_index(op.f('ix_image_etag'), 'image', ['etag'], unique=False)
    #op.drop_column('image', 'hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('image', sa.Column('hash', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_image_etag'), table_name='image')
    op.alter_column('image', 'etag', nullable=True, new_column_name='hash')
    op.create_index('ix_image_hash', 'image', ['hash'], unique=False)
    #op.drop_column('image', 'etag')
    # ### end Alembic commands ###
