"""Renamed organisation columns

Revision ID: 1c1d408e006e
Revises: a6f4740e5a6d
Create Date: 2023-10-04 14:52:50.756434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c1d408e006e'
down_revision = 'a6f4740e5a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey', 'root_organisation_id', new_column_name='organisation_id',existing_type=sa.Integer())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey', 'organisation_id', new_column_name='root_organisation_id',existing_type=sa.Integer())
    # ### end Alembic commands ###
