"""Added task info to task table.

Revision ID: 1db67e23ad73
Revises: bb1b2fef9de3
Create Date: 2020-03-09 07:06:46.729998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db67e23ad73'
down_revision = 'bb1b2fef9de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('live_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'live_flag')
    # ### end Alembic commands ###
