"""Added Mturk HITIDs and worker IDs

Revision ID: 1fa4148ac80b
Revises: 5c4bdb9bcd69
Create Date: 2019-12-03 08:42:12.251025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa4148ac80b'
down_revision = '5c4bdb9bcd69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('hit_id', sa.String(length=30), nullable=True))
    op.add_column('turkcode', sa.Column('worker_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turkcode', 'worker_id')
    op.drop_column('turkcode', 'hit_id')
    # ### end Alembic commands ###
