"""Added survey status

Revision ID: 1ff976871302
Revises: bfb2c8312fb3
Create Date: 2020-04-14 11:05:16.568712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff976871302'
down_revision = 'bfb2c8312fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('status', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'status')
    # ### end Alembic commands ###
