"""added date cols to survey

Revision ID: 219e72161b15
Revises: ae475ac95f9b
Create Date: 2025-09-23 11:49:18.693198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '219e72161b15'
down_revision = 'ae475ac95f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('survey', sa.Column('end_date', sa.DateTime(), nullable=True))

    op.create_index(op.f('ix_survey_end_date'), 'survey', ['end_date'], unique=False)
    op.create_index(op.f('ix_survey_start_date'), 'survey', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_start_date'), table_name='survey')
    op.drop_index(op.f('ix_survey_end_date'), table_name='survey')

    op.drop_column('survey', 'end_date')
    op.drop_column('survey', 'start_date')
    # ### end Alembic commands ###
