"""Added user_id to Surveys

Revision ID: 21f55993d43b
Revises: 53e175aeef7c
Create Date: 2020-01-31 14:24:23.157857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f55993d43b'
down_revision = '53e175aeef7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'survey', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='foreignkey')
    op.drop_column('survey', 'user_id')
    # ### end Alembic commands ###
