"""Added organisations and user permissions

Revision ID: 241fdce9a9a4
Revises: ff1c9bd5c934
Create Date: 2023-10-04 12:27:49.924265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '241fdce9a9a4'
down_revision = 'ff1c9bd5c934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('root_user_id', sa.Integer(), nullable=True),
        sa.Column('affiliation', sa.String(length=64), nullable=True),
        sa.Column('regions', sa.String(length=128), nullable=True),
        sa.Column('folder', sa.String(length=64), nullable=True),
        sa.Column('cloud_access', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['root_user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_folder'), 'organisation', ['folder'], unique=True)
    op.create_index(op.f('ix_organisation_root_user_id'), 'organisation', ['root_user_id'], unique=False)
    op.create_table('user_permissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organisation_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('delete', sa.Boolean(), nullable=True),
        sa.Column('create', sa.Boolean(), nullable=True),
        sa.Column('annotation', sa.Boolean(), nullable=True),
        sa.Column('default', sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_organisation_id'), 'user_permissions', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_table('survey_permission_exception',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('survey_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('permission', sa.String(length=8), nullable=True),
        sa.Column('annotate', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_permission_exception_survey_id'), 'survey_permission_exception', ['survey_id'], unique=False)
    op.create_index(op.f('ix_survey_permission_exception_user_id'), 'survey_permission_exception', ['user_id'], unique=False)
    op.create_table('survey_share',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('survey_id', sa.Integer(), nullable=True),
        sa.Column('organisation_id', sa.Integer(), nullable=True),
        sa.Column('write', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
        sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_share_organisation_id'), 'survey_share', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_survey_share_survey_id'), 'survey_share', ['survey_id'], unique=False)
    op.add_column('earth_ranger', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_earth_ranger_organisation_id'), 'earth_ranger', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'earth_ranger', 'organisation', ['organisation_id'], ['id'])
    op.add_column('survey', sa.Column('root_organisation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_survey_root_organisation_id'), 'survey', ['root_organisation_id'], unique=False)
    op.create_foreign_key(None, 'survey', 'organisation', ['root_organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='foreignkey')
    op.drop_index(op.f('ix_survey_root_organisation_id'), table_name='survey')
    op.drop_column('survey', 'root_organisation_id')
    op.drop_constraint(None, 'earth_ranger', type_='foreignkey')
    op.drop_index(op.f('ix_earth_ranger_organisation_id'), table_name='earth_ranger')
    op.drop_column('earth_ranger', 'organisation_id')
    op.drop_index(op.f('ix_survey_share_survey_id'), table_name='survey_share')
    op.drop_index(op.f('ix_survey_share_organisation_id'), table_name='survey_share')
    op.drop_table('survey_share')
    op.drop_index(op.f('ix_survey_permission_exception_user_id'), table_name='survey_permission_exception')
    op.drop_index(op.f('ix_survey_permission_exception_survey_id'), table_name='survey_permission_exception')
    op.drop_table('survey_permission_exception')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_organisation_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_organisation_root_user_id'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_folder'), table_name='organisation')
    op.drop_table('organisation')
    # ### end Alembic commands ###
