"""turkcode qualifications

Revision ID: 24a0c018730d
Revises: f15a5551f0b4
Create Date: 2019-11-14 13:23:42.670420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a0c018730d'
down_revision = 'f15a5551f0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('qualtification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turkcode', 'qualtification')
    # ### end Alembic commands ###
