"""Added worker qualifications for self hosting

Revision ID: 256f3cce4deb
Revises: eca51b193987
Create Date: 2020-09-29 08:56:47.431065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256f3cce4deb'
down_revision = 'eca51b193987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workersTable',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], ),
    sa.UniqueConstraint('user_id', 'worker_id')
    )
    op.create_index(op.f('ix_workersTable_user_id'), 'workersTable', ['user_id'], unique=False)
    op.create_index(op.f('ix_detectionLabels_labelgroup_id'), 'detectionLabels', ['labelgroup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detectionLabels_labelgroup_id'), table_name='detectionLabels')
    op.drop_index(op.f('ix_workersTable_user_id'), table_name='workersTable')
    op.drop_table('workersTable')
    # ### end Alembic commands ###
