"""added folder column to survey table

Revision ID: 26f1c4c42907
Revises: b4bfe9e942bf
Create Date: 2024-04-19 07:36:15.360764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f1c4c42907'
down_revision = 'b4bfe9e942bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('folder', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'folder')
    # ### end Alembic commands ###
