"""Added best detection pair to individual similarities table.

Revision ID: 279ea599fe95
Revises: fd82a173b6d3
Create Date: 2021-08-26 08:58:31.118509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279ea599fe95'
down_revision = 'fd82a173b6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ind_similarity', sa.Column('detection_1', sa.Integer(), nullable=True))
    op.add_column('ind_similarity', sa.Column('detection_2', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ind_similarity_detection_1'), 'ind_similarity', ['detection_1'], unique=False)
    op.create_index(op.f('ix_ind_similarity_detection_2'), 'ind_similarity', ['detection_2'], unique=False)
    op.create_foreign_key(None, 'ind_similarity', 'detection', ['detection_1'], ['id'])
    op.create_foreign_key(None, 'ind_similarity', 'detection', ['detection_2'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ind_similarity', type_='foreignkey')
    op.drop_constraint(None, 'ind_similarity', type_='foreignkey')
    op.drop_index(op.f('ix_ind_similarity_detection_2'), table_name='ind_similarity')
    op.drop_index(op.f('ix_ind_similarity_detection_1'), table_name='ind_similarity')
    op.drop_column('ind_similarity', 'detection_2')
    op.drop_column('ind_similarity', 'detection_1')
    # ### end Alembic commands ###
