"""Added qualifications

Revision ID: 2a0855ff40d9
Revises: 68448e5d1b94
Create Date: 2019-11-15 07:09:04.136815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0855ff40d9'
down_revision = '68448e5d1b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_label_id'), 'qualification', ['label_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualification_label_id'), table_name='qualification')
    op.drop_table('qualification')
    # ### end Alembic commands ###
