"""Added images_processing column to syrvey table

Revision ID: 2df4efa2ece3
Revises: 5872141603f6
Create Date: 2022-01-21 18:24:50.084120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df4efa2ece3'
down_revision = '5872141603f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('images_processing', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'images_processing')
    # ### end Alembic commands ###
