"""Changed Turkcodes to use task ids.

Revision ID: 30366be060af
Revises: 720eb9ae1950
Create Date: 2020-03-03 07:05:48.418032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30366be060af'
down_revision = '720eb9ae1950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('turkcode_ibfk_1', 'turkcode', type_='foreignkey')
    op.drop_index('ix_turkcode_survey_id', table_name='turkcode')
    op.drop_column('turkcode', 'survey_id')
    op.add_column('turkcode', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'turkcode', 'task', ['task_id'], ['id'])
    op.create_index(op.f('ix_turkcode_task_id'), 'turkcode', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('survey_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'turkcode', type_='foreignkey')
    op.create_foreign_key('turkcode_ibfk_1', 'turkcode', 'survey', ['survey_id'], ['id'])
    op.create_index('ix_turkcode_survey_id', 'turkcode', ['survey_id'], unique=False)
    op.drop_index(op.f('ix_turkcode_task_id'), table_name='turkcode')
    op.drop_column('turkcode', 'task_id')
    # ### end Alembic commands ###
