"""Removed qualification table

Revision ID: 3145c86e6e07
Revises: 9203da0b7e18
Create Date: 2021-11-29 11:13:14.080515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3145c86e6e07'
down_revision = '9203da0b7e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detection_ibfk_2', 'detection', type_='foreignkey')
    op.drop_index('ix_detection_qualification_id', table_name='detection')
    # op.drop_index('ix_qualification_label_id', table_name='qualification')
    op.drop_table('qualification')
    op.drop_column('detection', 'qualification_id')
    op.drop_column('task', 'qualification_size')
    op.drop_column('turkcode', 'qualification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('qualification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('qualification_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('detection', sa.Column('qualification_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('detection_ibfk_2', 'detection', 'qualification', ['qualification_id'], ['id'])
    op.create_index('ix_detection_qualification_id', 'detection', ['qualification_id'], unique=False)
    op.create_table('qualification',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('label_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name='qualification_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qualification_label_id', 'qualification', ['label_id'], unique=False)
    # ### end Alembic commands ###
