"""added label counts to the label and task tables

Revision ID: 31b4864e162c
Revises: 5fecd56d84e3
Create Date: 2023-02-24 11:43:44.700321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b4864e162c'
down_revision = '5fecd56d84e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('potential_clusters', sa.Integer(), nullable=True))
    op.add_column('label', sa.Column('image_count', sa.Integer(), nullable=True))
    op.add_column('label', sa.Column('sighting_count', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('potential_vhl_clusters', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('vhl_image_count', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('vhl_sighting_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'vhl_sighting_count')
    op.drop_column('task', 'vhl_image_count')
    op.drop_column('task', 'potential_vhl_clusters')
    op.drop_column('label', 'sighting_count')
    op.drop_column('label', 'image_count')
    op.drop_column('label', 'potential_clusters')
    # ### end Alembic commands ###
