"""Added unidentified individuals count column to label column

Revision ID: 3273b92ffa23
Revises: 31b4864e162c
Create Date: 2023-02-27 10:05:11.460464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3273b92ffa23'
down_revision = '31b4864e162c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('unidentified_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'unidentified_count')
    # ### end Alembic commands ###
