"""Added user-level notifications

Revision ID: 37f2ecaef547
Revises: 7ac86b24d8e0
Create Date: 2023-10-09 12:32:26.725518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f2ecaef547'
down_revision = '7ac86b24d8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('seen', sa.Boolean(), nullable=True))
    op.add_column('notification', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notification_seen'), 'notification', ['seen'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_seen'), table_name='notification')
    op.drop_column('notification', 'user_id')
    op.drop_column('notification', 'seen')
    # ### end Alembic commands ###
