"""added skipped column to cluster table

Revision ID: 3ef633a8eb16
Revises: b12966e60cdb
Create Date: 2022-05-19 15:39:02.407648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef633a8eb16'
down_revision = 'b12966e60cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('skipped', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_cluster_skipped'), 'cluster', ['skipped'], unique=False)
    op.create_index(op.f('ix_detectionTags_tag_id'), 'detectionTags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detectionTags_tag_id'), table_name='detectionTags')
    op.drop_index(op.f('ix_cluster_skipped'), table_name='cluster')
    op.drop_column('cluster', 'skipped')
    # ### end Alembic commands ###
