"""Added sitegroups table

Revision ID: 40f08ba28826
Revises: cb359a5b6428
Create Date: 2023-08-30 13:38:42.864707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40f08ba28826'
down_revision = 'cb359a5b6428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitegroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siteGroupings',
    sa.Column('trapgroup_id', sa.Integer(), nullable=True),
    sa.Column('sitegroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sitegroup_id'], ['sitegroup.id'], ),
    sa.ForeignKeyConstraint(['trapgroup_id'], ['trapgroup.id'], ),
    sa.UniqueConstraint('sitegroup_id', 'trapgroup_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siteGroupings')
    op.drop_table('sitegroup')
    # ### end Alembic commands ###
