"""Added classifier table

Revision ID: 425aaaff394f
Revises: 924c63cc0704
Create Date: 2022-10-20 14:30:57.471926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425aaaff394f'
down_revision = '924c63cc0704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ami_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifier_name'), 'classifier', ['name'], unique=True)
    op.create_index(op.f('ix_classifier_region'), 'classifier', ['region'], unique=False)
    op.create_index(op.f('ix_classifier_source'), 'classifier', ['source'], unique=False)
    op.add_column('survey', sa.Column('classifier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'survey', 'classifier', ['classifier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='foreignkey')
    op.drop_column('survey', 'classifier_id')
    op.drop_index(op.f('ix_classifier_source'), table_name='classifier')
    op.drop_index(op.f('ix_classifier_region'), table_name='classifier')
    op.drop_index(op.f('ix_classifier_name'), table_name='classifier')
    op.drop_table('classifier')
    # ### end Alembic commands ###
