"""change source column in detection table to a string

Revision ID: 453dd41cdd32
Revises: 977dc6c8d3c1
Create Date: 2020-02-18 13:02:13.628042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453dd41cdd32'
down_revision = '977dc6c8d3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('source', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection', 'source')
    # ### end Alembic commands ###
