"""added survey type column

Revision ID: 4643351c7899
Revises: 4f2c86a295d9
Create Date: 2025-02-12 09:34:36.437761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4643351c7899'
down_revision = '4f2c86a295d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'type')
    # ### end Alembic commands ###
