"""Added api key table

Revision ID: 4a299e32bf94
Revises: 8b07f1a39293
Create Date: 2024-08-08 13:10:20.039680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a299e32bf94'
down_revision = '8b07f1a39293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=32), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_api_key'), 'api_key', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_key_ibfk_1', 'api_key', type_='foreignkey')
    op.drop_index(op.f('ix_api_key_api_key'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
