"""added features and primary dets to indivs

Revision ID: 4adfc8483b0c
Revises: d3b9c4bb4b8c
Create Date: 2025-05-22 13:26:53.360372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '4adfc8483b0c'
down_revision = 'd3b9c4bb4b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('shape', Geometry(geometry_type='POLYGON', srid=32734, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_feature_detection_id'), 'feature', ['detection_id'], unique=False)

    op.create_table('individualPrimaryDetections',
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ),
    sa.ForeignKeyConstraint(['individual_id'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('detection_id', 'individual_id')
    )
    op.create_index('ix_individualPrimaryDetections_detection_id', 'individualPrimaryDetections', ['detection_id'], unique=False)
    op.create_index('ix_individualPrimaryDetections_individual_id', 'individualPrimaryDetections', ['individual_id'], unique=False)

    op.add_column('individual', sa.Column('primary_selected', sa.Boolean(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('individual', 'primary_selected')
    op.drop_constraint('individualPrimaryDetections_ibfk_2', 'individualPrimaryDetections', type_='foreignkey')
    op.drop_constraint('individualPrimaryDetections_ibfk_1', 'individualPrimaryDetections', type_='foreignkey')
    op.drop_index('ix_individualPrimaryDetections_individual_id', table_name='individualPrimaryDetections')
    op.drop_index('ix_individualPrimaryDetections_detection_id', table_name='individualPrimaryDetections')
    op.drop_table('individualPrimaryDetections')
    op.drop_constraint('feature_ibfk_1', 'feature', type_='foreignkey')
    op.drop_index(op.f('ix_feature_detection_id'), table_name='feature')
    op.drop_table('feature')
    # ### end Alembic commands ###
