"""Added affiliation column to user table

Revision ID: 4d7481502753
Revises: c8a6d3a907ff
Create Date: 2022-09-27 09:39:19.408421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7481502753'
down_revision = 'c8a6d3a907ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('affiliation', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'affiliation')
    # ### end Alembic commands ###
