"""Added delete column to to turkcodes

Revision ID: 4dd401e1455a
Revises: d77a8191ea48
Create Date: 2020-05-27 08:17:42.830399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd401e1455a'
down_revision = 'd77a8191ea48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('delete', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_turkcode_delete'), 'turkcode', ['delete'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turkcode_delete'), table_name='turkcode')
    op.drop_column('turkcode', 'delete')
    # ### end Alembic commands ###
