"""added archive col to org

Revision ID: 4f2c86a295d9
Revises: e46fa2e0e726
Create Date: 2024-11-20 12:53:09.330338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f2c86a295d9'
down_revision = 'e46fa2e0e726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('archive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'archive')
    # ### end Alembic commands ###
