"""Added organisational data to statistics table

Revision ID: 50c7b0a0ce29
Revises: d3930edea26d
Create Date: 2024-01-08 15:00:37.125485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50c7b0a0ce29'
down_revision = 'd3930edea26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistic', 'active_user_count', new_column_name='active_organisation_count',existing_type=sa.Integer())
    op.add_column('statistic', sa.Column('organisation_count', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('unique_daily_organisation_logins', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('average_daily_organisation_logins', sa.Float(), nullable=True))
    op.add_column('statistic', sa.Column('unique_monthly_organisation_logins', sa.Float(), nullable=True))
    op.create_index(op.f('ix_statistic_organisation_count'), 'statistic', ['organisation_count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistic_organisation_count'), table_name='statistic')
    op.drop_column('statistic', 'unique_monthly_organisation_logins')
    op.drop_column('statistic', 'average_daily_organisation_logins')
    op.drop_column('statistic', 'unique_daily_organisation_logins')
    op.drop_column('statistic', 'organisation_count')
    op.alter_column('statistic', 'active_organisation_count', new_column_name='active_user_count',existing_type=sa.Integer())
    # ### end Alembic commands ###
