"""Added more aws cost columns

Revision ID: 54bdbcdbc0b2
Revises: bdbf400554db
Create Date: 2024-07-11 14:04:09.714141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54bdbcdbc0b2'
down_revision = 'bdbf400554db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('textract_cost', sa.Float(), nullable=True))
    op.add_column('statistic', sa.Column('other_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'other_cost')
    op.drop_column('statistic', 'textract_cost')
    # ### end Alembic commands ###
