"""Added checked column to clusters for knocked analysis

Revision ID: 574eda4c991a
Revises: 6f2d5652c7e5
Create Date: 2020-08-31 20:10:02.678567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574eda4c991a'
down_revision = '6f2d5652c7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('checked', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_cluster_checked'), 'cluster', ['checked'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_checked'), table_name='cluster')
    op.drop_column('cluster', 'checked')
    # ### end Alembic commands ###
