"""Added image hash colum, and camera flagged colum

Revision ID: 584c99bed245
Revises: f2a59d4dd981
Create Date: 2021-06-23 15:33:03.888782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584c99bed245'
down_revision = 'f2a59d4dd981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('flagged', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_camera_flagged'), 'camera', ['flagged'], unique=False)
    op.add_column('image', sa.Column('hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_image_hash'), 'image', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_hash'), table_name='image')
    op.drop_column('image', 'hash')
    op.drop_index(op.f('ix_camera_flagged'), table_name='camera')
    op.drop_column('camera', 'flagged')
    # ### end Alembic commands ###
