"""Added bucket column to user table.

Revision ID: 5872141603f6
Revises: 3145c86e6e07
Create Date: 2021-12-02 07:36:34.808986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5872141603f6'
down_revision = '3145c86e6e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bucket', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_bucket'), 'user', ['bucket'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bucket'), table_name='user')
    op.drop_column('user', 'bucket')
    # ### end Alembic commands ###
