"""Added detections to qualification tests

Revision ID: 59c0a37156e7
Revises: 0455d2c7075d
Create Date: 2019-11-18 14:23:30.582497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c0a37156e7'
down_revision = '0455d2c7075d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('qualification_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_detection_qualification_id'), 'detection', ['qualification_id'], unique=False)
    op.create_foreign_key(None, 'detection', 'qualification', ['qualification_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection', type_='foreignkey')
    op.drop_index(op.f('ix_detection_qualification_id'), table_name='detection')
    op.drop_column('detection', 'qualification_id')
    # ### end Alembic commands ###
