"""Added correct_timestamps column to surveys table

Revision ID: 5aa673177d88
Revises: 584c99bed245
Create Date: 2021-06-24 16:14:51.546866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa673177d88'
down_revision = '584c99bed245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('correct_timestamps', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'correct_timestamps')
    # ### end Alembic commands ###
