"""Added hotkeys and parents to labels

Revision ID: 5c4bdb9bcd69
Revises: 59c0a37156e7
Create Date: 2019-11-20 08:29:00.826286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4bdb9bcd69'
down_revision = '59c0a37156e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('hotkey', sa.String(length=1), nullable=True))
    op.add_column('label', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_label_parent_id'), 'label', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'label', 'label', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'label', type_='foreignkey')
    op.drop_index(op.f('ix_label_parent_id'), table_name='label')
    op.drop_column('label', 'parent_id')
    op.drop_column('label', 'hotkey')
    # ### end Alembic commands ###
