"""added index to detection source

Revision ID: 5f7b326be9de
Revises: 8a735d68fa8a
Create Date: 2022-07-29 09:15:03.986401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7b326be9de'
down_revision = '8a735d68fa8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_detection_source'), 'detection', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_source'), table_name='detection')
    # ### end Alembic commands ###
