"""Added some task count columns

Revision ID: 5fecd56d84e3
Revises: 70808b81d280
Create Date: 2023-02-21 15:42:51.033389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fecd56d84e3'
down_revision = '70808b81d280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('unchecked_multi_count', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('unlabelled_animal_cluster_count', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('vhl_count', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('infoless_count', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('infoless_vhl_count', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('vhl_bounding_count', sa.Integer(), nullable=True))
    op.drop_column('task', 'download_available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('download_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('task', 'vhl_bounding_count')
    op.drop_column('task', 'infoless_vhl_count')
    op.drop_column('task', 'infoless_count')
    op.drop_column('task', 'vhl_count')
    op.drop_column('task', 'unlabelled_animal_cluster_count')
    op.drop_column('task', 'unchecked_multi_count')
    # ### end Alembic commands ###
