"""Added download available column to task table

Revision ID: 63d5be617c46
Revises: b54e2feb64ed
Create Date: 2023-01-16 07:44:07.235878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d5be617c46'
down_revision = 'b54e2feb64ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('download_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'download_available')
    # ### end Alembic commands ###
