"""Improving many-to-many relationships

Revision ID: 658e386d4e7f
Revises: 1db67e23ad73
Create Date: 2020-03-09 11:59:49.076206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658e386d4e7f'
down_revision = '1db67e23ad73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'images', ['image_id', 'cluster_id'])
    op.create_unique_constraint(None, 'tags', ['tag_id', 'cluster_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'images', type_='unique')
    # ### end Alembic commands ###
