"""Added detection-level tagging information

Revision ID: 65902996a655
Revises: 574eda4c991a
Create Date: 2020-09-16 08:19:40.536198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65902996a655'
down_revision = '574eda4c991a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labelgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labelgroup_checked'), 'labelgroup', ['checked'], unique=False)
    op.create_index(op.f('ix_labelgroup_detection_id'), 'labelgroup', ['detection_id'], unique=False)
    op.create_index(op.f('ix_labelgroup_task_id'), 'labelgroup', ['task_id'], unique=False)
    op.create_table('detectionLabels',
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('labelgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['labelgroup_id'], ['labelgroup.id'], ),
    sa.UniqueConstraint('label_id', 'labelgroup_id')
    )
    op.create_index(op.f('ix_detectionLabels_label_id'), 'detectionLabels', ['label_id'], unique=False)
    op.add_column('task', sa.Column('is_bounding', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_task_is_bounding'), 'task', ['is_bounding'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_is_bounding'), table_name='task')
    op.drop_column('task', 'is_bounding')
    op.drop_index(op.f('ix_detectionLabels_label_id'), table_name='detectionLabels')
    op.drop_table('detectionLabels')
    op.drop_index(op.f('ix_labelgroup_task_id'), table_name='labelgroup')
    op.drop_index(op.f('ix_labelgroup_detection_id'), table_name='labelgroup')
    op.drop_index(op.f('ix_labelgroup_checked'), table_name='labelgroup')
    op.drop_table('labelgroup')
    # ### end Alembic commands ###
