"""Added active column to Individual table.

Revision ID: 67e54367c4b4
Revises: b3c8bd410ef5
Create Date: 2021-05-10 16:28:54.013179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e54367c4b4'
down_revision = 'b3c8bd410ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_individual_active'), 'individual', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individual_active'), table_name='individual')
    op.drop_column('individual', 'active')
    # ### end Alembic commands ###
