"""user status

Revision ID: 68448e5d1b94
Revises: 24a0c018730d
Create Date: 2019-11-14 13:58:58.229462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68448e5d1b94'
down_revision = '24a0c018730d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passed', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'passed')
    # ### end Alembic commands ###
