"""Removed classifier version column from survey table

Revision ID: 6ace6183b08d
Revises: a97ee0f666f3
Create Date: 2022-11-02 10:59:54.625828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ace6183b08d'
down_revision = 'a97ee0f666f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'classifier_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('classifier_version', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
