"""added lambda cost col

Revision ID: 6b4d23c56357
Revises: e99cc85ae260
Create Date: 2024-10-29 05:38:36.737638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b4d23c56357'
down_revision = 'e99cc85ae260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('lambda_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'lambda_cost')
    # ### end Alembic commands ###
