"""Added trapgroup coordinates.

Revision ID: 6f2d5652c7e5
Revises: f05b321416f1
Create Date: 2020-08-04 14:01:39.601483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2d5652c7e5'
down_revision = 'f05b321416f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trapgroup', sa.Column('altitude', sa.Float(), nullable=True))
    op.add_column('trapgroup', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('trapgroup', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trapgroup', 'longitude')
    op.drop_column('trapgroup', 'latitude')
    op.drop_column('trapgroup', 'altitude')
    # ### end Alembic commands ###
