"""Added download column to image table

Revision ID: 70808b81d280
Revises: e001a2dfb5da
Create Date: 2023-02-21 09:36:01.269815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70808b81d280'
down_revision = 'e001a2dfb5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('downloaded', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_image_downloaded'), 'image', ['downloaded'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_downloaded'), table_name='image')
    op.drop_column('image', 'downloaded')
    # ### end Alembic commands ###
