"""Added Tasks.

Revision ID: 720eb9ae1950
Revises: 453dd41cdd32
Create Date: 2020-03-02 12:19:59.162378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '720eb9ae1950'
down_revision = '453dd41cdd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=True)
    op.create_index(op.f('ix_task_survey_id'), 'task', ['survey_id'], unique=False)
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'cluster_id')
    )
    op.add_column('cluster', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cluster_task_id'), 'cluster', ['task_id'], unique=False)
    op.create_foreign_key(None, 'cluster', 'task', ['task_id'], ['id'])
    op.drop_constraint('image_ibfk_2', 'image', type_='foreignkey')
    op.drop_column('image', 'cluster_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('cluster_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('image_ibfk_2', 'image', 'cluster', ['cluster_id'], ['id'])
    op.drop_constraint(None, 'cluster', type_='foreignkey')
    op.drop_index(op.f('ix_cluster_task_id'), table_name='cluster')
    op.drop_column('cluster', 'task_id')
    op.drop_table('images')
    op.drop_index(op.f('ix_task_survey_id'), table_name='task')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
