"""changed_masks_to_use_cameragroups

Revision ID: 734aa220c3ef
Revises: 08247764954a
Create Date: 2024-01-31 12:22:10.687922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '734aa220c3ef'
down_revision = '08247764954a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('mask', sa.Column('cameragroup_id', sa.Integer(), nullable=True))

    op.drop_index('mask_ibfk_1', table_name='mask')

    op.create_index(op.f('ix_mask_cameragroup_id'), 'mask', ['cameragroup_id'], unique=False)
    op.create_foreign_key(None, 'mask', 'cameragroup', ['cameragroup_id'], ['id'])
    op.drop_column('mask', 'camera_id')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # op.add_column('mask', sa.Column('camera_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('mask_ibfk_1', 'mask', type_='foreignkey')
    op.drop_index(op.f('ix_mask_cameragroup_id'), table_name='mask')

    op.create_index('mask_ibfk_1', 'mask', ['camera_id'], unique=False)

    op.drop_column('mask', 'cameragroup_id')
   
    # ### end Alembic commands ###
