"""added queue and version columns to classifier table

Revision ID: 745522c04e34
Revises: 863b2c63ab60
Create Date: 2024-10-04 11:38:47.736238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745522c04e34'
down_revision = '863b2c63ab60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifier', sa.Column('version', sa.Float(), nullable=True))
    op.add_column('classifier', sa.Column('queue', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_classifier_queue'), 'classifier', ['queue'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifier_queue'), table_name='classifier')
    op.drop_column('classifier', 'queue')
    op.drop_column('classifier', 'version')
    # ### end Alembic commands ###
