"""added classification translations table.

Revision ID: 749cd00d04f0
Revises: a1a26b206b6e
Create Date: 2021-01-12 10:24:33.139156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749cd00d04f0'
down_revision = 'a1a26b206b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_classification'), 'translation', ['classification'], unique=False)
    op.create_index(op.f('ix_translation_label_id'), 'translation', ['label_id'], unique=False)
    op.create_index(op.f('ix_translation_task_id'), 'translation', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_task_id'), table_name='translation')
    op.drop_index(op.f('ix_translation_label_id'), table_name='translation')
    op.drop_index(op.f('ix_translation_classification'), table_name='translation')
    op.drop_table('translation')
    # ### end Alembic commands ###
