"""added caching columns for distance count display in annot  set details table

Revision ID: 76e7c632a395
Revises: 41f781754d20
Create Date: 2026-08-11 13:26:52.289076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76e7c632a395'
down_revision = '41f781754d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('distance_count', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('vhl_distance_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'vhl_distance_count')
    op.drop_column('label', 'distance_count')
    # ### end Alembic commands ###
