"""added complete columns to tasks and labels

Revision ID: 7a858eb2441f
Revises: fc1420f6fbf0
Create Date: 2020-07-02 17:27:13.883736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a858eb2441f'
down_revision = 'fc1420f6fbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('complete', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'complete')
    op.drop_column('label', 'complete')
    # ### end Alembic commands ###
