"""changed surveyshare permission column to string


Revision ID: 7ac86b24d8e0
Revises: 1c1d408e006e
Create Date: 2023-10-05 11:13:50.644469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ac86b24d8e0'
down_revision = '1c1d408e006e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_permission_exception', sa.Column('annotation', sa.Boolean(), nullable=True))
    op.drop_column('survey_permission_exception', 'annotate')
    op.add_column('survey_share', sa.Column('permission', sa.String(length=8), nullable=True))
    op.drop_column('survey_share', 'write')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_share', sa.Column('write', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('survey_share', 'permission')
    op.add_column('survey_permission_exception', sa.Column('annotate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('survey_permission_exception', 'annotation')
    # ### end Alembic commands ###
