"""Added tagging time to tasks.

Revision ID: 7cd5443ad09f
Revises: 1ff976871302
Create Date: 2020-04-20 14:01:21.980446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd5443ad09f'
down_revision = '1ff976871302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('tagging_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'tagging_time')
    # ### end Alembic commands ###
