"""Added cloud_access column to user table

Revision ID: 821bbc400a8d
Revises: 40f08ba28826
Create Date: 2023-09-29 13:03:46.521397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '821bbc400a8d'
down_revision = '40f08ba28826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cloud_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cloud_access')
    # ### end Alembic commands ###
