"""added_masks

Revision ID: 844df6612d7b
Revises: d3930edea26d
Create Date: 2023-12-06 05:53:22.804986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '844df6612d7b'
down_revision = 'd3930edea26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('shape', Geometry(geometry_type='POLYGON', srid=32734, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mask_camera_id'), 'mask', ['camera_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mask_camera_id'), table_name='mask')
    op.drop_table('mask')

    # ### end Alembic commands ###
