"""Added new stats columns to stats and users tables

Revision ID: 856a486a6387
Revises: cb359a5b6428
Create Date: 2023-08-01 10:57:29.527279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '856a486a6387'
down_revision = 'cb359a5b6428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('unique_daily_logins', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('unique_daily_admin_logins', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('average_daily_logins', sa.Float(), nullable=True))
    op.add_column('statistic', sa.Column('average_daily_admin_logins', sa.Float(), nullable=True))
    op.add_column('statistic', sa.Column('unique_monthly_logins', sa.Float(), nullable=True))
    op.add_column('statistic', sa.Column('unique_monthly_admin_logins', sa.Float(), nullable=True))
    op.create_index(op.f('ix_statistic_user_count'), 'statistic', ['user_count'], unique=False)
    op.add_column('user', sa.Column('image_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('previous_image_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'previous_image_count')
    op.drop_column('user', 'image_count')
    op.drop_index(op.f('ix_statistic_user_count'), table_name='statistic')
    op.drop_column('statistic', 'unique_monthly_admin_logins')
    op.drop_column('statistic', 'unique_monthly_logins')
    op.drop_column('statistic', 'average_daily_admin_logins')
    op.drop_column('statistic', 'average_daily_logins')
    op.drop_column('statistic', 'unique_daily_admin_logins')
    op.drop_column('statistic', 'unique_daily_logins')
    # ### end Alembic commands ###
