"""Added threshold column to classification label table

Revision ID: 863b2c63ab60
Revises: 1172a4cef6c4
Create Date: 2024-09-30 14:42:53.922679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '863b2c63ab60'
down_revision = '1172a4cef6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification_label', sa.Column('threshold', sa.Float(), nullable=True))
    op.drop_column('classifier', 'threshold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifier', sa.Column('threshold', mysql.FLOAT(), nullable=True))
    op.drop_column('classification_label', 'threshold')
    # ### end Alembic commands ###
