"""Added celery info to task table

Revision ID: 87f4c249b047
Revises: e5cf9e97638b
Create Date: 2020-03-28 09:17:37.497084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f4c249b047'
down_revision = 'e5cf9e97638b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('celery_task', sa.String(length=64), nullable=True))
    op.add_column('task', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    op.drop_column('task', 'celery_task')
    # ### end Alembic commands ###
