"""Increased tagging_level size

Revision ID: 8b07f1a39293
Revises: f2c7e531e336
Create Date: 2024-08-19 13:15:01.071808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b07f1a39293'
down_revision = 'f2c7e531e336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'tagging_level',
               existing_type=sa.VARCHAR(length=32, collation='latin1_swedish_ci'),
               type_=sa.VARCHAR(length=80, collation='latin1_swedish_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'tagging_level',
               existing_type=sa.VARCHAR(length=80, collation='latin1_swedish_ci'),
               type_=sa.VARCHAR(length=32, collation='latin1_swedish_ci'),
               existing_nullable=True)