"""Made Labels many-to-many.

Revision ID: 8cb9fffabfd9
Revises: eec89812cfc3
Create Date: 2020-03-10 09:52:52.680950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cb9fffabfd9'
down_revision = 'eec89812cfc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.UniqueConstraint('label_id', 'cluster_id')
    )
    op.drop_constraint('cluster_ibfk_1', 'cluster', type_='foreignkey')
    op.drop_index('ix_cluster_label_id', table_name='cluster')
    op.drop_column('cluster', 'label_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('label_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('cluster_ibfk_1', 'cluster', 'label', ['label_id'], ['id'])
    op.create_index('ix_cluster_label_id', 'cluster', ['label_id'], unique=False)
    op.drop_table('labels')
    # ### end Alembic commands ###
