"""added calibration_code to survey

Revision ID: 8d09aa2d5947
Revises: edc2b66d548c
Create Date: 2026-07-01 12:16:04.988934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d09aa2d5947'
down_revision = 'edc2b66d548c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('calibration_code', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'calibration_code')
    # ### end Alembic commands ###
