"""Added llava field to image table and renamed video extracted field

Revision ID: 91c228481869
Revises: 0dae8a55964f
Create Date: 2024-03-05 06:55:36.938054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91c228481869'
down_revision = '0dae8a55964f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('llava_data', sa.String(length=128), nullable=True))
    op.alter_column('video', 'extracted_timestamp', nullable=True, new_column_name='extracted_text',existing_type=sa.String(length=64))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'extracted_text', nullable=True, new_column_name='extracted_timestamp',existing_type=sa.String(length=64))
    op.drop_column('image', 'llava_data')
    # ### end Alembic commands ###
