"""Added a bunch of columns to allow for stateless operation.

Revision ID: 9203da0b7e18
Revises: c6808bf3aa12
Create Date: 2021-09-06 08:28:15.666444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9203da0b7e18'
down_revision = 'c6808bf3aa12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ind_similarity', sa.Column('old_score', sa.Float(), nullable=True))
    op.add_column('ind_similarity', sa.Column('skipped', sa.Boolean(), nullable=True))
    op.add_column('ind_similarity', sa.Column('allocated', sa.Integer(), nullable=True))
    op.add_column('ind_similarity', sa.Column('allocation_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_ind_similarity_allocated'), 'ind_similarity', ['allocated'], unique=False)
    op.create_index(op.f('ix_ind_similarity_allocation_timestamp'), 'ind_similarity', ['allocation_timestamp'], unique=False)
    op.create_index(op.f('ix_ind_similarity_skipped'), 'ind_similarity', ['skipped'], unique=False)
    op.create_foreign_key(None, 'ind_similarity', 'user', ['allocated'], ['id'])
    op.add_column('individual', sa.Column('allocated', sa.Integer(), nullable=True))
    op.add_column('individual', sa.Column('allocation_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_individual_allocated'), 'individual', ['allocated'], unique=False)
    op.create_index(op.f('ix_individual_allocation_timestamp'), 'individual', ['allocation_timestamp'], unique=False)
    op.create_foreign_key(None, 'individual', 'user', ['allocated'], ['id'])
    op.add_column('task', sa.Column('jobs_finished', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('current_name', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'current_name')
    op.drop_column('task', 'jobs_finished')
    op.drop_constraint(None, 'individual', type_='foreignkey')
    op.drop_index(op.f('ix_individual_allocation_timestamp'), table_name='individual')
    op.drop_index(op.f('ix_individual_allocated'), table_name='individual')
    op.drop_column('individual', 'allocation_timestamp')
    op.drop_column('individual', 'allocated')
    op.drop_constraint(None, 'ind_similarity', type_='foreignkey')
    op.drop_index(op.f('ix_ind_similarity_skipped'), table_name='ind_similarity')
    op.drop_index(op.f('ix_ind_similarity_allocation_timestamp'), table_name='ind_similarity')
    op.drop_index(op.f('ix_ind_similarity_allocated'), table_name='ind_similarity')
    op.drop_column('ind_similarity', 'allocation_timestamp')
    op.drop_column('ind_similarity', 'allocated')
    op.drop_column('ind_similarity', 'skipped')
    op.drop_column('ind_similarity', 'old_score')
    # ### end Alembic commands ###
