"""Removed classification_checked column and added ai_check_complete

Revision ID: 924c63cc0704
Revises: 96315d1473a2
Create Date: 2022-10-05 11:54:24.936540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '924c63cc0704'
down_revision = '96315d1473a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cluster_classification_checked', table_name='cluster')
    op.drop_column('cluster', 'classification_checked')
    op.add_column('task', sa.Column('ai_check_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'ai_check_complete')
    op.add_column('cluster', sa.Column('classification_checked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_cluster_classification_checked', 'cluster', ['classification_checked'], unique=False)
    # ### end Alembic commands ###
