"""Added static column to detections

Revision ID: 946bc1d207d1
Revises: 21f55993d43b
Create Date: 2020-02-06 10:00:39.107041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946bc1d207d1'
down_revision = '21f55993d43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('static', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection', 'static')
    # ### end Alembic commands ###
