"""added_staticgroups

Revision ID: 9622455aef8e
Revises: e37a04faa52c
Create Date: 2024-02-08 06:15:10.979799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9622455aef8e'
down_revision = 'e37a04faa52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staticgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staticgroup_status'), 'staticgroup', ['status'], unique=False)
    op.create_index(op.f('ix_staticgroup_user_id'), 'staticgroup', ['user_id'], unique=False)

    op.add_column('detection', sa.Column('staticgroup_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_detection_staticgroup_id'), 'detection', ['staticgroup_id'], unique=False)
    op.create_foreign_key(None, 'detection', 'staticgroup', ['staticgroup_id'], ['id'])
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection', type_='foreignkey')
    op.drop_index(op.f('ix_detection_staticgroup_id'), table_name='detection')
    op.drop_column('detection', 'staticgroup_id')
    op.drop_index(op.f('ix_staticgroup_user_id'), table_name='staticgroup')
    op.drop_index(op.f('ix_staticgroup_status'), table_name='staticgroup')
    op.drop_table('staticgroup')
    # ### end Alembic commands ###
