"""Added regions column to user table

Revision ID: 96315d1473a2
Revises: 4d7481502753
Create Date: 2022-09-27 13:32:00.371098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96315d1473a2'
down_revision = '4d7481502753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('regions', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'regions')
    # ### end Alembic commands ###
