"""Added downloaded and hash columns to video table

Revision ID: 966f1254c74c
Revises: 6542e06f36f7
Create Date: 2023-05-03 09:02:51.581895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966f1254c74c'
down_revision = '6542e06f36f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('hash', sa.String(length=64), nullable=True))
    op.add_column('video', sa.Column('downloaded', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_video_downloaded'), 'video', ['downloaded'], unique=False)
    op.create_index(op.f('ix_video_hash'), 'video', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_hash'), table_name='video')
    op.drop_index(op.f('ix_video_downloaded'), table_name='video')
    op.drop_column('video', 'downloaded')
    op.drop_column('video', 'hash')
    # ### end Alembic commands ###

