"""empty message

Revision ID: 977dc6c8d3c1
Revises: 946bc1d207d1
Create Date: 2020-02-18 13:00:38.354833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '977dc6c8d3c1'
down_revision = '946bc1d207d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detection_source', table_name='detection')
    op.drop_column('detection', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('source', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_detection_source', 'detection', ['source'], unique=False)
    # ### end Alembic commands ###
