"""added_child_labels_col

Revision ID: 9a1a9f9f469c
Revises: acb4e414a502
Create Date: 2026-04-16 08:57:14.841103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a1a9f9f469c'
down_revision = 'acb4e414a502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('include_child_labels', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'include_child_labels')
    # ### end Alembic commands ###
