"""user bucket migration. Also removed identify pool id column

Revision ID: 9a728770bba1
Revises: 5f7b326be9de
Create Date: 2022-08-18 06:59:26.067115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a728770bba1'
down_revision = '5f7b326be9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('folder', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_bucket', table_name='user')
    op.create_index(op.f('ix_user_folder'), 'user', ['folder'], unique=True)
    op.drop_column('user', 'bucket')
    op.drop_column('user', 'identity_pool_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('identity_pool_id', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('bucket', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_folder'), table_name='user')
    op.create_index('ix_user_bucket', 'user', ['bucket'], unique=False)
    op.drop_column('user', 'folder')
    # ### end Alembic commands ###
