"""Added classification column to cluster table

Revision ID: a1a26b206b6e
Revises: f2b1d411d6d0
Create Date: 2021-01-11 15:38:24.781571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a26b206b6e'
down_revision = 'f2b1d411d6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('classification', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_cluster_classification'), 'cluster', ['classification'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_classification'), table_name='cluster')
    op.drop_column('cluster', 'classification')
    # ### end Alembic commands ###
