"""Added processing_initialised column to surveys table

Revision ID: a1c174321e5f
Revises: 2df4efa2ece3
Create Date: 2022-02-01 19:36:38.919716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c174321e5f'
down_revision = '2df4efa2ece3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('processing_initialised', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'processing_initialised')
    # ### end Alembic commands ###
