"""Added image count columns to organisation table

Revision ID: a6f4740e5a6d
Revises: 241fdce9a9a4
Create Date: 2023-10-04 13:57:57.873007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6f4740e5a6d'
down_revision = '241fdce9a9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('image_count', sa.Integer(), nullable=True))
    op.add_column('organisation', sa.Column('previous_image_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'previous_image_count')
    op.drop_column('organisation', 'image_count')
    # ### end Alembic commands ###
