"""Added active and threshold columns to the classifier table

Revision ID: a97ee0f666f3
Revises: 425aaaff394f
Create Date: 2022-10-26 09:01:12.472583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97ee0f666f3'
down_revision = '425aaaff394f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifier', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('classifier', sa.Column('threshold', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_classifier_active'), 'classifier', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifier_active'), table_name='classifier')
    op.drop_column('classifier', 'threshold')
    op.drop_column('classifier', 'active')
    # ### end Alembic commands ###
