"""added organisationClassifiers

Revision ID: acb4e414a502
Revises: 219e72161b15
Create Date: 2026-02-03 13:17:23.568097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acb4e414a502'
down_revision = '219e72161b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisationClassifiers',
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('classifier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classifier_id'], ['classifier.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.UniqueConstraint('organisation_id', 'classifier_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisationClassifiers')
    # ### end Alembic commands ###
