"""added areas and id cols

Revision ID: ae475ac95f9b
Revises: 4adfc8483b0c
Create Date: 2025-08-11 09:25:22.341743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae475ac95f9b'
down_revision = '4adfc8483b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('survey', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_survey_area_id'), 'survey', ['area_id'], unique=False)
    op.create_foreign_key('fk_survey_area', 'survey', 'area', ['area_id'], ['id'])

    op.add_column('label', sa.Column('indID_allowed', sa.Boolean(), nullable=True))

    op.add_column('task', sa.Column('areaID_library', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_task_areaID_library'), 'task', ['areaID_library'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_areaID_library'), table_name='task')
    op.drop_column('task', 'areaID_library')

    op.drop_column('label', 'indID_allowed')

    op.drop_constraint('fk_survey_area', 'survey', type_='foreignkey')
    op.drop_index(op.f('ix_survey_area_id'), table_name='survey')
    op.drop_column('survey', 'area_id')
    op.drop_table('area')
    # ### end Alembic commands ###
