"""Added classifier version to survey table.

Revision ID: ae6fb2e3bd84
Revises: 0c9610b64864
Create Date: 2020-12-08 13:31:49.253378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6fb2e3bd84'
down_revision = '0c9610b64864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('classifier_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'classifier_version')
    # ### end Alembic commands ###
