"""Added tags to labelgroups and skipped column to clusters

Revision ID: b12966e60cdb
Revises: a1c174321e5f
Create Date: 2022-05-12 07:30:56.857760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12966e60cdb'
down_revision = 'a1c174321e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detectionTags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('labelgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labelgroup_id'], ['labelgroup.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.UniqueConstraint('tag_id', 'labelgroup_id')
    )
    op.create_index(op.f('ix_detectionTags_labelgroup_id'), 'detectionTags', ['labelgroup_id'], unique=False)
    op.create_index(op.f('ix_detectionTags_tag_id'), 'detectionTags', ['tag_id'], unique=False)
    op.add_column('cluster', sa.Column('skipped', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_cluster_skipped'), 'cluster', ['skipped'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_skipped'), table_name='cluster')
    op.drop_column('cluster', 'skipped')
    op.drop_index(op.f('ix_detectionTags_tag_id'), table_name='detectionTags')
    op.drop_index(op.f('ix_detectionTags_labelgroup_id'), table_name='detectionTags')
    op.drop_table('detectionTags')
    # ### end Alembic commands ###
