"""Added auto-annotation info to db.

Revision ID: b2d9ece117c0
Revises: 67e54367c4b4
Create Date: 2021-05-19 11:34:36.928966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d9ece117c0'
down_revision = '67e54367c4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('parent_classification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'parent_classification')
    # ### end Alembic commands ###
