"""Added video and frame count columns to survey table

Revision ID: b3540e3a7ec5
Revises: 40ac30febb0b
Create Date: 2023-05-10 08:00:10.365652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3540e3a7ec5'
down_revision = '40ac30febb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('frame_count', sa.Integer(), nullable=True))
    op.add_column('survey', sa.Column('video_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'video_count')
    op.drop_column('survey', 'frame_count')
    # ### end Alembic commands ###
