"""Added user and timestamp info to individual table.

Revision ID: b3c8bd410ef5
Revises: b6ef9c5b606a
Create Date: 2021-04-28 10:51:46.386236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c8bd410ef5'
down_revision = 'b6ef9c5b606a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('individual', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_individual_user_id'), 'individual', ['user_id'], unique=False)
    op.create_foreign_key(None, 'individual', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'individual', type_='foreignkey')
    op.drop_index(op.f('ix_individual_user_id'), table_name='individual')
    op.drop_column('individual', 'user_id')
    op.drop_column('individual', 'timestamp')
    # ### end Alembic commands ###
