"""changed llava_data to extracted_data in image table

Revision ID: b4bfe9e942bf
Revises: fcdbdb8ac2dd
Create Date: 2024-03-27 09:03:24.691908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4bfe9e942bf'
down_revision = 'fcdbdb8ac2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('image', 'llava_data', nullable=True, new_column_name='extracted_data', existing_type=sa.String(length=128))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('image', 'extracted_data', nullable=True, new_column_name='llava_data', existing_type=sa.String(length=128))

    # ### end Alembic commands ###
