"""Addedclass_check_count column to task table

Revision ID: b54e2feb64ed
Revises: 6ace6183b08d
Create Date: 2022-11-10 10:38:38.214012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54e2feb64ed'
down_revision = '6ace6183b08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('class_check_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'class_check_count')
    # ### end Alembic commands ###
