"""Added similarities.

Revision ID: b6ef9c5b606a
Revises: 06614d80dad0
Create Date: 2021-04-23 16:05:00.173929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ef9c5b606a'
down_revision = '06614d80dad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ind_similarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_1', sa.Integer(), nullable=True),
    sa.Column('individual_2', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['individual_1'], ['individual.id'], ),
    sa.ForeignKeyConstraint(['individual_2'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ind_similarity_individual_1'), 'ind_similarity', ['individual_1'], unique=False)
    op.create_index(op.f('ix_ind_similarity_individual_2'), 'ind_similarity', ['individual_2'], unique=False)
    op.create_index(op.f('ix_ind_similarity_score'), 'ind_similarity', ['score'], unique=False)
    op.create_table('det_similarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_1', sa.Integer(), nullable=True),
    sa.Column('detection_2', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['detection_1'], ['detection.id'], ),
    sa.ForeignKeyConstraint(['detection_2'], ['detection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_det_similarity_detection_1'), 'det_similarity', ['detection_1'], unique=False)
    op.create_index(op.f('ix_det_similarity_detection_2'), 'det_similarity', ['detection_2'], unique=False)
    op.create_index(op.f('ix_det_similarity_score'), 'det_similarity', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_det_similarity_score'), table_name='det_similarity')
    op.drop_index(op.f('ix_det_similarity_detection_2'), table_name='det_similarity')
    op.drop_index(op.f('ix_det_similarity_detection_1'), table_name='det_similarity')
    op.drop_table('det_similarity')
    op.drop_index(op.f('ix_ind_similarity_score'), table_name='ind_similarity')
    op.drop_index(op.f('ix_ind_similarity_individual_2'), table_name='ind_similarity')
    op.drop_index(op.f('ix_ind_similarity_individual_1'), table_name='ind_similarity')
    op.drop_table('ind_similarity')
    # ### end Alembic commands ###
