"""Removing depricated db columns

Revision ID: bad821e2a9be
Revises: 256f3cce4deb
Create Date: 2020-10-13 13:52:47.316696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bad821e2a9be'
down_revision = '256f3cce4deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'live_flag')
    op.drop_column('task', 'celery_task')
    op.drop_index('ix_turkcode_delete', table_name='turkcode')
    op.drop_column('turkcode', 'delete')
    op.drop_column('turkcode', 'code')
    op.drop_column('turkcode', 'worker_id')
    op.drop_column('turkcode', 'hit_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('hit_id', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('turkcode', sa.Column('worker_id', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('turkcode', sa.Column('code', mysql.VARCHAR(length=24), nullable=False))
    op.add_column('turkcode', sa.Column('delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_turkcode_delete', 'turkcode', ['delete'], unique=False)
    op.add_column('task', sa.Column('celery_task', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('task', sa.Column('live_flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
