"""Added detection status.

Revision ID: baeb6832abcc
Revises: bad821e2a9be
Create Date: 2020-10-16 16:04:04.787552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baeb6832abcc'
down_revision = 'bad821e2a9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('status', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_detection_status'), 'detection', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_status'), table_name='detection')
    op.drop_column('detection', 'status')
    # ### end Alembic commands ###
