"""Made labels task dependent.

Revision ID: bb1b2fef9de3
Revises: 30366be060af
Create Date: 2020-03-06 12:02:19.047530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1b2fef9de3'
down_revision = '30366be060af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_label_task_id'), 'label', ['task_id'], unique=False)
    op.create_foreign_key(None, 'label', 'task', ['task_id'], ['id'])
    op.add_column('tag', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tag_task_id'), 'tag', ['task_id'], unique=False)
    op.create_foreign_key(None, 'tag', 'task', ['task_id'], ['id'])
    op.add_column('task', sa.Column('qualification_size', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('tagging_level', sa.String(length=32), nullable=True))
    op.add_column('task', sa.Column('test_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'test_size')
    op.drop_column('task', 'tagging_level')
    op.drop_column('task', 'size')
    op.drop_column('task', 'qualification_size')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_index(op.f('ix_tag_task_id'), table_name='tag')
    op.drop_column('tag', 'task_id')
    op.drop_constraint(None, 'label', type_='foreignkey')
    op.drop_index(op.f('ix_label_task_id'), table_name='label')
    op.drop_column('label', 'task_id')
    # ### end Alembic commands ###
