"""Added zip id to images

Revision ID: bd927ddaffc4
Revises: fedc7296d073
Create Date: 2024-07-31 13:27:12.566075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd927ddaffc4'
down_revision = 'fedc7296d073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('zip_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_image_zip_id'), 'image', ['zip_id'], unique=False)
    op.create_foreign_key(None, 'image', 'zip', ['zip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_index(op.f('ix_image_zip_id'), table_name='image')
    op.drop_column('image', 'zip_id')
    # ### end Alembic commands ###
