"""added indexes to classificationLabel table

Revision ID: bdbf400554db
Revises: 745522c04e34
Create Date: 2024-10-17 11:13:13.625451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbf400554db'
down_revision = '745522c04e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_classification_label_classification'), 'classification_label', ['classification'], unique=False)
    op.create_index(op.f('ix_classification_label_classifier_id'), 'classification_label', ['classifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classification_label_classifier_id'), table_name='classification_label')
    op.drop_index(op.f('ix_classification_label_classification'), table_name='classification_label')
    # ### end Alembic commands ###
