"""added EarthRanger ID table

Revision ID: c274c6c24350
Revises: 50c7b0a0ce29
Create Date: 2024-01-19 13:21:44.455997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c274c6c24350'
down_revision = '50c7b0a0ce29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_rangerID',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('api_key', sa.String(length=32), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_rangerID_api_key'), 'e_rangerID', ['api_key'], unique=False)
    op.create_index(op.f('ix_e_rangerID_cluster_id'), 'e_rangerID', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_e_rangerID_cluster_id'), table_name='e_rangerID')
    op.drop_index(op.f('ix_e_rangerID_api_key'), table_name='e_rangerID')
    op.drop_table('e_rangerID')
    # ### end Alembic commands ###
