"""added_mask_checked

Revision ID: c66b766c196a
Revises: 1ca142deef18
Create Date: 2023-12-05 05:50:32.180957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c66b766c196a'
down_revision = '1ca142deef18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('mask', sa.Column('checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('mask', 'checked')

    # ### end Alembic commands ###
