"""Added cluster allocation to user table

Revision ID: c6808bf3aa12
Revises: 279ea599fe95
Create Date: 2021-09-01 19:01:55.212740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6808bf3aa12'
down_revision = '279ea599fe95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('clusters_allocated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'clusters_allocated')
    # ### end Alembic commands ###
