"""Added still_rate to video and removed fps and frame_count

Revision ID: c6da7222b204
Revises: 26f1c4c42907
Create Date: 2024-04-24 13:40:49.722239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6da7222b204'
down_revision = '26f1c4c42907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('still_rate', sa.Float(), nullable=True))
    op.drop_column('video', 'frame_count')
    op.drop_column('video', 'fps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('fps', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('frame_count', sa.Integer(), nullable=True))
    op.drop_column('video', 'still_rate')
    # ### end Alembic commands ###
