"""Added empty_count and restore cols

Revision ID: c772fca1e336
Revises: bd927ddaffc4
Create Date: 2024-08-01 06:35:51.396041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c772fca1e336'
down_revision = 'bd927ddaffc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('id_restore', sa.DateTime(), nullable=True))
    op.add_column('survey', sa.Column('download_restore', sa.DateTime(), nullable=True))
    op.add_column('survey', sa.Column('edit_restore', sa.DateTime(), nullable=True))
    op.add_column('survey', sa.Column('empty_restore', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('empty_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'empty_count')
    op.drop_column('survey', 'empty_restore')
    op.drop_column('survey', 'edit_restore')
    op.drop_column('survey', 'download_restore')
    op.drop_column('survey', 'id_restore')
    # ### end Alembic commands ###
