"""Added cost columns to the statistics table

Revision ID: c8a6d3a907ff
Revises: dbcbb67ff961
Create Date: 2022-09-26 09:27:02.566693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a6d3a907ff'
down_revision = 'dbcbb67ff961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('server_cost', sa.Float(), nullable=True))
    op.add_column('statistic', sa.Column('storage_cost', sa.Float(), nullable=True))
    op.add_column('statistic', sa.Column('db_cost', sa.Float(), nullable=True))
    op.add_column('statistic', sa.Column('total_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'total_cost')
    op.drop_column('statistic', 'db_cost')
    op.drop_column('statistic', 'storage_cost')
    op.drop_column('statistic', 'server_cost')
    # ### end Alembic commands ###
