"""added_cameragroups

Revision ID: cb204d4f6298
Revises: dbda7bd631a8
Create Date: 2024-02-08 05:50:45.545418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb204d4f6298'
down_revision = 'dbda7bd631a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameragroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('camera', sa.Column('cameragroup_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_camera_cameragroup_id'), 'camera', ['cameragroup_id'], unique=False)
    op.create_foreign_key(None, 'camera', 'cameragroup', ['cameragroup_id'], ['id'])

    op.add_column('survey', sa.Column('camera_code', sa.String(length=256), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('survey', 'camera_code')
    op.drop_constraint(None, 'camera', type_='foreignkey')
    op.drop_index(op.f('ix_camera_cameragroup_id'), table_name='camera')
    op.drop_column('camera', 'cameragroup_id')
    op.drop_table('cameragroup')
    # ### end Alembic commands ###
