"""added id column back to individual similarities

Revision ID: cb359a5b6428
Revises: df50ff634df2
Create Date: 2023-07-04 12:23:51.167483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb359a5b6428'
down_revision = 'df50ff634df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PRIMARY', 'ind_similarity', type_='primary')
    op.alter_column('ind_similarity', 'individual_1',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ind_similarity', 'individual_2',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.execute("ALTER TABLE ind_similarity ADD id INT PRIMARY KEY AUTO_INCREMENT;")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ind_similarity', 'id')
    op.alter_column('ind_similarity', 'individual_2',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ind_similarity', 'individual_1',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###

