"""added notifications table

Revision ID: cf2bc80015af
Revises: 039ce4e121cc
Create Date: 2022-08-26 07:51:52.065000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf2bc80015af'
down_revision = '039ce4e121cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contents', sa.String(length=2048), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_expires'), 'notification', ['expires'], unique=False)
    op.create_table('userNotifications',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.UniqueConstraint('user_id', 'notification_id')
    )
    op.create_index(op.f('ix_userNotifications_user_id'), 'userNotifications', ['user_id'], unique=False)
    op.drop_column('user', 'last_notification_read')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_notification_read', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_userNotifications_user_id'), table_name='userNotifications')
    op.drop_table('userNotifications')
    op.drop_index(op.f('ix_notification_expires'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
