"""Added detection_rating to images and required_images to clusters.

Revision ID: cfbc687866ae
Revises: c0f2872c74d4
Create Date: 2021-02-10 13:08:32.165723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfbc687866ae'
down_revision = 'c0f2872c74d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requiredimagestable',
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.UniqueConstraint('image_id', 'cluster_id')
    )
    op.create_index(op.f('ix_requiredimagestable_image_id'), 'requiredimagestable', ['image_id'], unique=False)
    op.add_column('image', sa.Column('detection_rating', sa.Float(), nullable=True))
    op.create_index(op.f('ix_image_detection_rating'), 'image', ['detection_rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_detection_rating'), table_name='image')
    op.drop_column('image', 'detection_rating')
    op.drop_index(op.f('ix_requiredimagestable_image_id'), table_name='requiredimagestable')
    op.drop_table('requiredimagestable')
    # ### end Alembic commands ###
