"""added classification_checked column to Cluster table

Revision ID: d0af964d2508
Revises: 749cd00d04f0
Create Date: 2021-01-12 10:47:26.933728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0af964d2508'
down_revision = '749cd00d04f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('classification_checked', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_cluster_classification_checked'), 'cluster', ['classification_checked'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_classification_checked'), table_name='cluster')
    op.drop_column('cluster', 'classification_checked')
    # ### end Alembic commands ###
