"""Added auto_classify column to Translation table

Revision ID: d1c986c70ef7
Revises: b2d9ece117c0
Create Date: 2021-05-19 13:00:05.042317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c986c70ef7'
down_revision = 'b2d9ece117c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation', sa.Column('auto_classify', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_translation_auto_classify'), 'translation', ['auto_classify'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_auto_classify'), table_name='translation')
    op.drop_column('translation', 'auto_classify')
    # ### end Alembic commands ###
