"""Removed unique requirement for user emails

Revision ID: d3930edea26d
Revises: 37f2ecaef547
Create Date: 2023-10-24 07:12:57.634683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3930edea26d'
down_revision = '37f2ecaef547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
