"""Added trigger_source column to surveys table

Revision ID: d3b9c4bb4b8c
Revises: 0e4cdc7aae95
Create Date: 2025-04-30 06:08:56.661657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b9c4bb4b8c'
down_revision = '0e4cdc7aae95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('trigger_source', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'trigger_source')
    # ### end Alembic commands ###
