"""Improved DB indexing

Revision ID: d77a8191ea48
Revises: 0723835f30da
Create Date: 2020-05-08 15:51:42.400251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77a8191ea48'
down_revision = '0723835f30da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cluster_lastAssigned', table_name='cluster')
    op.create_index(op.f('ix_detection_score'), 'detection', ['score'], unique=False)
    op.create_index(op.f('ix_detection_static'), 'detection', ['static'], unique=False)
    op.create_index(op.f('ix_image_corrected_timestamp'), 'image', ['corrected_timestamp'], unique=False)
    op.create_index(op.f('ix_images_image_id'), 'images', ['image_id'], unique=False)
    op.create_index(op.f('ix_labels_label_id'), 'labels', ['label_id'], unique=False)
    op.create_index(op.f('ix_tags_tag_id'), 'tags', ['tag_id'], unique=False)
    op.drop_index('ix_task_name', table_name='task')
    op.create_index(op.f('ix_trapgroup_active'), 'trapgroup', ['active'], unique=False)
    op.create_index(op.f('ix_trapgroup_processing'), 'trapgroup', ['processing'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trapgroup_processing'), table_name='trapgroup')
    op.drop_index(op.f('ix_trapgroup_active'), table_name='trapgroup')
    op.create_index('ix_task_name', 'task', ['name'], unique=False)
    op.drop_index(op.f('ix_tags_tag_id'), table_name='tags')
    op.drop_index(op.f('ix_labels_label_id'), table_name='labels')
    op.drop_index(op.f('ix_images_image_id'), table_name='images')
    op.drop_index(op.f('ix_image_corrected_timestamp'), table_name='image')
    op.drop_index(op.f('ix_detection_static'), table_name='detection')
    op.drop_index(op.f('ix_detection_score'), table_name='detection')
    op.create_index('ix_cluster_lastAssigned', 'cluster', ['lastAssigned'], unique=False)
    # ### end Alembic commands ###
