"""Added icID_count column to label table

Revision ID: d96f6080bb9a
Revises: af7f298c1620
Create Date: 2023-03-31 14:32:44.763205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96f6080bb9a'
down_revision = 'af7f298c1620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('icID_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'icID_count')
    # ### end Alembic commands ###
