"""Added statistics table and init_complete column to task table

Revision ID: dbcbb67ff961
Revises: cf2bc80015af
Create Date: 2022-09-20 14:27:23.627725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcbb67ff961'
down_revision = 'cf2bc80015af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('active_user_count', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistic_timestamp'), 'statistic', ['timestamp'], unique=False)
    op.add_column('task', sa.Column('init_complete', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_task_init_complete'), 'task', ['init_complete'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_init_complete'), table_name='task')
    op.drop_column('task', 'init_complete')
    op.drop_index(op.f('ix_statistic_timestamp'), table_name='statistic')
    op.drop_table('statistic')
    # ### end Alembic commands ###
