"""Added video data to statistics

Revision ID: dbda7bd631a8
Revises: c274c6c24350
Create Date: 2024-01-22 15:03:57.868161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbda7bd631a8'
down_revision = 'c274c6c24350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('previous_video_count', sa.Integer(), nullable=True))
    op.add_column('organisation', sa.Column('previous_frame_count', sa.Integer(), nullable=True))
    op.add_column('organisation', sa.Column('video_count', sa.Integer(), nullable=True))
    op.add_column('organisation', sa.Column('frame_count', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('video_count', sa.Integer(), nullable=True))
    op.add_column('statistic', sa.Column('frame_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'frame_count')
    op.drop_column('statistic', 'video_count')
    op.drop_column('organisation', 'frame_count')
    op.drop_column('organisation', 'video_count')
    op.drop_column('organisation', 'previous_frame_count')
    op.drop_column('organisation', 'previous_video_count')
    # ### end Alembic commands ###
