"""Added back hash column to image table

Revision ID: e001a2dfb5da
Revises: 19f5d9426d42
Create Date: 2023-02-17 12:18:15.881961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e001a2dfb5da'
down_revision = '19f5d9426d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_image_hash'), 'image', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_hash'), table_name='image')
    op.drop_column('image', 'hash')
    # ### end Alembic commands ###
