"""Added image count column to survey table

Revision ID: e220f73c7c5e
Revises: b12966e60cdb
Create Date: 2022-05-24 11:44:37.848588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e220f73c7c5e'
down_revision = 'b12966e60cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('image_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'image_count')
    # ### end Alembic commands ###
