"""added_masks

Revision ID: e37a04faa52c
Revises: cb204d4f6298
Create Date: 2024-02-08 06:05:16.274127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'e37a04faa52c'
down_revision = 'cb204d4f6298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cameragroup_id', sa.Integer(), nullable=True),
    sa.Column('shape', Geometry(geometry_type='POLYGON', srid=32734, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cameragroup_id'], ['cameragroup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_mask_cameragroup_id'), 'mask', ['cameragroup_id'], unique=False)
    # op.create_index(op.f('ix_mask_shape'), 'mask', ['shape'], unique=False)
    op.create_index(op.f('ix_mask_user_id'), 'mask', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mask', type_='foreignkey')
    op.drop_index(op.f('ix_mask_user_id'), table_name='mask')
    op.drop_index(op.f('ix_mask_shape'), table_name='mask')
    op.drop_index(op.f('ix_mask_cameragroup_id'), table_name='mask')
    op.drop_table('mask')
    # ### end Alembic commands ###
