"""Added sky and small detection mask columns to survey table

Revision ID: e5069ea36aef
Revises: e220f73c7c5e
Create Date: 2022-06-01 11:39:06.702161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5069ea36aef'
down_revision = 'e220f73c7c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('ignore_small_detections', sa.Boolean(), nullable=True))
    op.add_column('survey', sa.Column('sky_masked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'sky_masked')
    op.drop_column('survey', 'ignore_small_detections')
    # ### end Alembic commands ###
