"""Removed uniqueness from label and tag names

Revision ID: e5cf9e97638b
Revises: a8f7642b1815
Create Date: 2020-03-27 08:28:50.080409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cf9e97638b'
down_revision = 'a8f7642b1815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_label_description', table_name='label')
    op.create_index(op.f('ix_label_description'), 'label', ['description'], unique=False)
    op.drop_index('ix_tag_description', table_name='tag')
    op.create_index(op.f('ix_tag_description'), 'tag', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_description'), table_name='tag')
    op.create_index('ix_tag_description', 'tag', ['description'], unique=True)
    op.drop_index(op.f('ix_label_description'), table_name='label')
    op.create_index('ix_label_description', 'label', ['description'], unique=True)
    # ### end Alembic commands ###
