"""Added individuals to db.

Revision ID: e8a1a55fd4d6
Revises: cfbc687866ae
Create Date: 2021-03-31 17:26:49.693520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a1a55fd4d6'
down_revision = 'cfbc687866ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_label_id'), 'individual', ['label_id'], unique=False)
    op.create_index(op.f('ix_individual_task_id'), 'individual', ['task_id'], unique=False)
    op.create_table('individualTags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['individual_id'], ['individual.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.UniqueConstraint('tag_id', 'individual_id')
    )
    op.create_index(op.f('ix_individualTags_tag_id'), 'individualTags', ['tag_id'], unique=False)
    op.create_table('individual_parent_child',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['individual.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id'),
    sa.UniqueConstraint('parent_id', 'child_id')
    )
    op.create_table('individualDetections',
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ),
    sa.ForeignKeyConstraint(['individual_id'], ['individual.id'], ),
    sa.UniqueConstraint('detection_id', 'individual_id')
    )
    op.create_index(op.f('ix_individualDetections_detection_id'), 'individualDetections', ['detection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individualDetections_detection_id'), table_name='individualDetections')
    op.drop_table('individualDetections')
    op.drop_table('individual_parent_child')
    op.drop_index(op.f('ix_individualTags_tag_id'), table_name='individualTags')
    op.drop_table('individualTags')
    op.drop_index(op.f('ix_individual_task_id'), table_name='individual')
    op.drop_index(op.f('ix_individual_label_id'), table_name='individual')
    op.drop_table('individual')
    # ### end Alembic commands ###
