"""Modified survey & download_request tables

Revision ID: e99cc85ae260
Revises: 3835de1a3d6d
Create Date: 2024-10-11 11:44:07.655190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e99cc85ae260'
down_revision = '3835de1a3d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_request', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('download_request', sa.Column('celery_id', sa.String(length=64), nullable=True))
    op.add_column('survey', sa.Column('require_launch', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'require_launch')
    op.drop_column('download_request', 'celery_id')
    op.drop_column('download_request', 'name')
    # ### end Alembic commands ###
