"""Changed labels bridging table name

Revision ID: ea8a26cd539c
Revises: 65902996a655
Create Date: 2020-09-16 14:42:08.032177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea8a26cd539c'
down_revision = '65902996a655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_labels_label_id', table_name='labels')
    # op.drop_index('label_id', table_name='labels')
    op.rename_table('labels', 'labelstable')
    op.create_index(op.f('ix_labelstable_label_id'), 'labelstable', ['label_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labelstable_label_id'), table_name='labelstable')
    op.rename_table('labelstable', 'labels')
    op.create_index('label_id', 'labels', ['label_id', 'cluster_id'], unique=True)
    op.create_index('ix_labels_label_id', 'labels', ['label_id'], unique=False)
    # ### end Alembic commands ###
