"""Added columns to allow self-hosting

Revision ID: eca51b193987
Revises: ea8a26cd539c
Create Date: 2020-09-24 16:50:40.240267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca51b193987'
down_revision = 'ea8a26cd539c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_turkcode_active'), 'turkcode', ['active'], unique=False)
    op.add_column('user', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_parent_id'), 'user', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'user', 'user', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_parent_id'), table_name='user')
    op.drop_column('user', 'parent_id')
    op.drop_index(op.f('ix_turkcode_active'), table_name='turkcode')
    op.drop_column('turkcode', 'active')
    # ### end Alembic commands ###
