"""added_calibration_images_and_distance

Revision ID: edc2b66d548c
Revises: 9a1a9f9f469c
Create Date: 2026-06-26 12:44:23.889256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edc2b66d548c'
down_revision = '9a1a9f9f469c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cameragroup_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('top', sa.Float(), nullable=True),
    sa.Column('left', sa.Float(), nullable=True),
    sa.Column('bottom', sa.Float(), nullable=True),
    sa.Column('right', sa.Float(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cameragroup_id'], ['cameragroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_image_cameragroup_id'), 'calibration_image', ['cameragroup_id'], unique=False)
    op.add_column('detection', sa.Column('distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection', 'distance')
    op.drop_index(op.f('ix_calibration_image_cameragroup_id'), table_name='calibration_image')
    op.drop_table('calibration_image')
    # ### end Alembic commands ###
