"""Improving many-to-many relationships2

Revision ID: eec89812cfc3
Revises: 658e386d4e7f
Create Date: 2020-03-09 12:03:29.415378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eec89812cfc3'
down_revision = '658e386d4e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'cluster_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('images', 'image_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tags', 'cluster_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tags', 'tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tags', 'cluster_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('images', 'image_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('images', 'cluster_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
