"""Added trapgroup allocation to a user.

Revision ID: ef3069ebf3b4
Revises: 1423b6625c9e
Create Date: 2020-01-13 13:13:54.544243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef3069ebf3b4'
down_revision = '1423b6625c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#   op.drop_constraint('image_ibfk_3', 'image', type_='foreignkey')
#   op.drop_column('image', 'label_id')
    op.add_column('trapgroup', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trapgroup', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trapgroup', type_='foreignkey')
    op.drop_column('trapgroup', 'user_id')
    op.add_column('image', sa.Column('label_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('image_ibfk_3', 'image', 'label', ['label_id'], ['id'])
    # ### end Alembic commands ###
