"""Added AWS cognito pool credentials to user table

Revision ID: f05b321416f1
Revises: 7a858eb2441f
Create Date: 2020-07-09 09:58:04.838006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05b321416f1'
down_revision = '7a858eb2441f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('identity_pool_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'identity_pool_id')
    # ### end Alembic commands ###
