"""empty message

Revision ID: f15a5551f0b4
Revises: 
Create Date: 2019-11-05 11:44:51.107104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15a5551f0b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_description'), 'label', ['description'], unique=True)
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_name'), 'survey', ['name'], unique=True)
    op.create_table('turkcode',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_turkcode_user_id'), 'turkcode', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastAssigned', sa.DateTime(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_label_id'), 'cluster', ['label_id'], unique=False)
    op.create_index(op.f('ix_cluster_lastAssigned'), 'cluster', ['lastAssigned'], unique=False)
    op.create_index(op.f('ix_cluster_user_id'), 'cluster', ['user_id'], unique=False)
    op.create_table('trapgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('trapgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trapgroup_id'], ['trapgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_path'), 'camera', ['path'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('corrected_timestamp', sa.DateTime(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_camera_id'), 'image', ['camera_id'], unique=False)
    op.create_table('detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('top', sa.Float(), nullable=True),
    sa.Column('left', sa.Float(), nullable=True),
    sa.Column('right', sa.Float(), nullable=True),
    sa.Column('bottom', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_category'), 'detection', ['category'], unique=False)
    op.create_index(op.f('ix_detection_image_id'), 'detection', ['image_id'], unique=False)
    op.create_index(op.f('ix_detection_source'), 'detection', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_source'), table_name='detection')
    op.drop_index(op.f('ix_detection_image_id'), table_name='detection')
    op.drop_index(op.f('ix_detection_category'), table_name='detection')
    op.drop_table('detection')
    op.drop_index(op.f('ix_image_camera_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_camera_path'), table_name='camera')
    op.drop_table('camera')
    op.drop_table('trapgroup')
    op.drop_index(op.f('ix_cluster_user_id'), table_name='cluster')
    op.drop_index(op.f('ix_cluster_lastAssigned'), table_name='cluster')
    op.drop_index(op.f('ix_cluster_label_id'), table_name='cluster')
    op.drop_table('cluster')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_turkcode_user_id'), table_name='turkcode')
    op.drop_table('turkcode')
    op.drop_index(op.f('ix_survey_name'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_label_description'), table_name='label')
    op.drop_table('label')
    # ### end Alembic commands ###
