"""Added assigned time to turkcodes.

Revision ID: f2b1d411d6d0
Revises: ae6fb2e3bd84
Create Date: 2020-12-10 11:14:02.390812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b1d411d6d0'
down_revision = 'ae6fb2e3bd84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turkcode', sa.Column('assigned', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turkcode', 'assigned')
    # ### end Alembic commands ###
