"""Added icID first quantile complete col

Revision ID: f2c7e531e336
Revises: f94e7498856b
Create Date: 2024-07-01 11:39:22.514469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2c7e531e336'
down_revision = 'f94e7498856b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('icID_q1_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'icID_q1_complete')
    # ### end Alembic commands ###
