"""Added individual id algorithm col to label

Revision ID: f94e7498856b
Revises: 0ad045f609b9
Create Date: 2024-06-05 05:40:56.160389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f94e7498856b'
down_revision = '0ad045f609b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('algorithm', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'algorithm')
    # ### end Alembic commands ###
