"""Added queueing column to trapgroup table

Revision ID: fc1420f6fbf0
Revises: 4dd401e1455a
Create Date: 2020-05-28 17:44:45.370077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1420f6fbf0'
down_revision = '4dd401e1455a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trapgroup', sa.Column('queueing', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_trapgroup_queueing'), 'trapgroup', ['queueing'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trapgroup_queueing'), table_name='trapgroup')
    op.drop_column('trapgroup', 'queueing')
    # ### end Alembic commands ###
