"""added_staticgroups_for_static_detections

Revision ID: fc74be0b156e
Revises: 50c7b0a0ce29
Create Date: 2024-01-16 12:42:58.428012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc74be0b156e'
down_revision = '50c7b0a0ce29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staticgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staticgroup_status'), 'staticgroup', ['status'], unique=False)
    op.add_column('detection', sa.Column('staticgroup_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_detection_staticgroup_id'), 'detection', ['staticgroup_id'], unique=False)
    op.create_foreign_key(None, 'detection', 'staticgroup', ['staticgroup_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_staticgroup_id'), table_name='detection')
    op.drop_column('detection', 'staticgroup_id')
    op.drop_index(op.f('ix_staticgroup_status'), table_name='staticgroup')
    op.drop_table('staticgroup')
    # ### end Alembic commands ###
