"""added_extracted_and_skipped_flags_to_image

Revision ID: fcdbdb8ac2dd
Revises: 8ebf88f3d7bf
Create Date: 2024-03-15 13:13:31.208578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdbdb8ac2dd'
down_revision = '8ebf88f3d7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('skipped', sa.Boolean(), nullable=True))
    op.add_column('image', sa.Column('extracted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_image_extracted'), 'image', ['extracted'], unique=False)
    op.create_index(op.f('ix_image_skipped'), 'image', ['skipped'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_skipped'), table_name='image')
    op.drop_index(op.f('ix_image_extracted'), table_name='image')
    op.drop_column('image', 'extracted')
    op.drop_column('image', 'skipped')
    # ### end Alembic commands ###
