"""Added icID_allowed column to label table

Revision ID: fd82a173b6d3
Revises: 5aa673177d88
Create Date: 2021-07-22 15:30:18.146233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd82a173b6d3'
down_revision = '5aa673177d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('icID_allowed', sa.Boolean(), nullable=True))
    op.alter_column('turkcode', 'user_id',
               existing_type=mysql.VARCHAR(length=24),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turkcode', 'user_id',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)
    op.drop_column('label', 'icID_allowed')
    # ### end Alembic commands ###
