"""Added zip table

Revision ID: fedc7296d073
Revises: 54bdbcdbc0b2
Create Date: 2024-07-19 06:17:11.344471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fedc7296d073'
down_revision = '54bdbcdbc0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zip_survey_id'), 'zip', ['survey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zip_survey_id'), table_name='zip')
    op.drop_table('zip')
    # ### end Alembic commands ###
